### ISSUE TITLE
Opening EPUBs with DRM never completes on 2.0.0-beta.2

### ISSUE THREAD

**Issue by ettore** [readium/r2-shared-swift#136]
After upgrading to Xcode 12 + R2 `2.0.0-beta.2`, when i try to open a DRM-protected EPUB the reader now spins forever and never shows the book. This issue doesn't manifest in books without DRM. However, previously (Xcode 11 + `2.0.0-beta.1`) this issue did not manifest even for DRM books, and i have no changes in our app pre- and post- upgrade, beside what's required by the beta.2 migration guide. So I'm a little confused to what might cause this.

Upon some investigation, it appears that the `EPUBSpreadView::spreadDidLoad()` function is never called. The navigator transitions from:
```
🔎️ EPUBNavigatorViewController.swift:267:	-> on load
🔎️ EPUBNavigatorViewController.swift:167:	* transitioned to loading
```
but it never transitions to `loaded`. Specifically the `PaginationView::loadNextPage()` is called once but the `go(to:)` call never completes, and this closure in `EPUBSpreadView.swift:353` is also never called:
```
registerJSMessage(named: "spreadLoaded") { [weak self] in self?.spreadDidLoad($0) }
```
I'm wondering if something changed in the timing of DRM decryption and related tasks under the hood? I see there were some performance improvements added after `beta.1` but I wouldn't know if/how those affect DRM at all.

In my setup of the EPUBNavigatorViewController I am using a custom configuration, I disabled it in case it would affect it but it made no difference:
```
var config = EPUBNavigatorViewController.Configuration()
config.preloadPreviousPositionCount = 0
config.preloadNextPositionCount = 0
config.debugState = true
let navigator = EPUBNavigatorViewController(publication: publication,
                                            initialLocation: initialLocation,
                                            resourcesServer: resourcesServer,
                                            config: config)
```

**Comment by mickael-menu** [comment]
> We are using a [custom implementation of ContentProtection](https://github.com/NYPL-Simplified/Simplified-iOS/blob/develop/Simplified/Reader2/ReaderStackConfiguration/AdobeDRM/AdobeDRMContentProtection.swift) (for Adobe DRM), but no custom implementation of `Archive`. I can take a look if I need to fix anything on my end.

Thanks, I'll take a look into your implementation of the `ContentProtection` too.

> May I ask why you mention `MinizipArchive` in particular? I see there are other implementations of `Archive`. I'm just unfamiliar with that code.

An "Archive" can be a ZIP or RAR file, an exploded directory, etc. I assumed that you were working with EPUB (so a ZIP file) and `MinizipArchive` is the default implementation of a ZIP archive for Readium. There's also `ZIPFoundationArchive` but it's only a WIP at this stage.

Also the changes in the culprit PR are mostly related to ZIP.

> Also, are there going to be more non-bug fix changes in the next betas and until the final 2.0 release? I am a little surprised/worried to see this kind of breakages just going from one beta to the next.

There won't be much changes before the final 2.0.0 release. I just merged in a new HTTP service but it's mostly an addition and it should not impact existing features. Unfortunately, I'm mostly alone maintaining the Swift toolkit and don't have the bandwidth to go through careful release steps with proper Release Candidates. There's some pressure to release the 2.0.0. However, I'll make sure to release a 2.0.1 with only bug fixes quickly in case there are some bug reports with the 2.0.0.

You are also using a feature that is not well tested. As far as I know, NYPL is the only integrator with a custom `ContentProtection` service.

**Comment by mickael-menu** [comment]
I had a quick look at your `ContentProtection` and saw a couple potential issues, although I'm not sure this would have an impact on the bug you experience.

* You don't set a `ContentProtectionService` for the publication. This is necessary because otherwise the Publication is not considered as DRM-protected by Readium. Maybe it could cause some problems. Note that the implementation doesn't need to do much, [here's the one for LCP](https://github.com/readium/r2-lcp-swift/blob/b8adc686c392b3279f57259d6904af599b9737d3/readium-lcp-swift/Content%20Protection/LCPContentProtection.swift#L89). It is [added to the Publication here](https://github.com/readium/r2-lcp-swift/blob/b8adc686c392b3279f57259d6904af599b9737d3/readium-lcp-swift/Content%20Protection/LCPContentProtection.swift#L61-L65).
* Your `AdobeDRMFetcher` is not closing the underlying `ArchiveFetcher` in `AdobeDRMFetcher.close()`. Since you only want to transform the resources of the original fetcher, I suggest you use `TransformingFetcher` instead of implementing your own `Fetcher`, this way you make sure you will not forget to delegate any API to the original fetcher. [This is how LCP is creating the `TransformingFetcher`](https://github.com/readium/r2-lcp-swift/blob/b8adc686c392b3279f57259d6904af599b9737d3/readium-lcp-swift/Content%20Protection/LCPContentProtection.swift#L57-L60) and you just need to give a `(Resource) -> Resource` function as transformer.

Btw let me know how goes the test with:

```swift
let content = try! publication.get(publication.readingOrder.first!).readAsString().get()
```

**Comment by mickael-menu** [comment]
> yep I am working with EPUBs, so, good to know about Minizip, thanks. I'll take a look too at `MinizipArchive`. I wasn't sure mainly about the role of `ExplodedArchive` here.

You might try opening an exploded ACS-protected ZIP directory. This should automatically select `ExplodedArchive` and could help single out the culprit. Minizip has been a source of many frustrations/bugs but unfortunately there are not many ZIP solutions on iOS, with advanced APIs that we need (range random access).

Also, do you have the issue with LCP-protected publications as well or only ACS?

> I understand and can sympathize with the pain/burden. While I am just a "user" of the R2 frameworks, I'd be interested in knowing if I can help with the release process for RCs. I understand there's a weekly call tomorrow, if I can join I will.

You are already helping a lot by writing such detailed bug reports! But we really want to be an open community at Readium, and there's definitely room if you want to participate more actively. Tomorrow I'll be presenting a new `SearchService` API on the call.

**Comment by ettore** [comment]
The commit I linked hopefully answers the main requirement about the missing ContentProtectionService. My implementation is kinda dumb, but perhaps it's sufficient. Great catch on the missing `close` call. The actual thing that broke I believe was that the path to `META-INF/encryption.xml` now requires a leading slash.

I was tempted to try the `TransformingFetcher` because if that works it'll be less code on our end, which I always like, but it might not be the best moment for us (need to avoid delays).

**Comment by mickael-menu** [comment]
> My implementation is kinda dumb, but perhaps it's sufficient

Looks good. The nice thing is that now you can use `publication.isProtected` and `publication.protectionName` in your app if you need to do something for all protected publications, no matter the DRM. You should also be able to implement the `UserRights` interface later to support copying text while following ACS constraints.

> The actual thing that broke I believe was that the path to `META-INF/encryption.xml` now requires a leading slash.

Ha great catch, I did change this in the `Archive` implementations to be more consistent throughout the toolkit: every path relative to the root of a publication starts with a slash. I'm sorry I forgot to add this to the changelog.

> I was tempted to try the `TransformingFetcher` because if that works it'll be less code on our end, which I always like, but it might not be the best moment for us (need to avoid delays).

This should be fine for now. The `TransformingFetcher` is more future-proof if we add new APIs to `Fetcher`, but your implementation is fine.
