### ISSUE TITLE
Fix JSON parsing for OPDS 2.0

### ISSUE THREAD

**Issue by HadrienGardeur** [readium/r2-shared-swift#14]
With the upcoming PR (#13), we'll now be able to parse the RWPM manifest to transform it into our in-memory structure.

For now this is mostly used for OPDS 2.0, where it seems to be broken.

This can be tested in the Test App using the OPDS 2.0 Test Catalog: https://feedbooks.github.io/opds-test-catalog/opds-2/home.json

More specifically, the publications feed is meant to test as many edge cases as possible: https://feedbooks.github.io/opds-test-catalog/opds-2/publications.json

This Epic will probably have to remain open for some time, as we gradually add more test cases and related issues to it.

**Comment by aferditamuriqi** [comment]
closing this Epic, as all issues connected have been addressed and merged.

**Comment by HadrienGardeur** [comment]
I would keep that one open for now, since I don't think that we can consider the OPDS 2.0 implementation to be tested. 

There's no harm in keeping such issues in "Review/QA" or in "Done" rather than closing them in Zenhub.

**Comment by aferditamuriqi** [comment]
I would rather re-open new issues if they occur as it is getting already quite time-consuming to review and merge and close etc. existing ones.

**Comment by HadrienGardeur** [comment]
But this one is purely a way we can tag all the bugs related to OPDS 2.0 parsing. I can handle it and close it when I feel it's truly ready if it makes things easier.

**Comment by aferditamuriqi** [comment]
it doesn't really because I still have to go through all of it every time I review issues and PRs etc. I don't really see the benefit of keeping it around, where we should create new issues as they appear.
