### ISSUE TITLE
Links parsing inside a collection is broken

### ISSUE THREAD

**Issue by gbugniot** [readium/r2-shared-swift#18]
OPDS 2 parser throws `OPDS2ParserError.invalidCollection` with this `links` key:

![fb_json.png](https://images.zenhubusercontent.com/5ad468d84b5806bc2bcf3756/23e28b69-f2e9-43a1-a979-66084f9365ad)

**Comment by llemeurfr** [comment]
I suppose that series links are not yet in our model. if it is the case, the parser should not choke when seeing unknown structures.

**Comment by HadrienGardeur** [comment]
@llemeurfr that's not the case, series are part of the current model: https://github.com/readium/r2-shared-swift/blob/master/r2-shared-swift/BelongsTo.swift#L13

**Comment by gbugniot** [comment]
If you take a look at the [related parser code](https://github.com/readium/readium-opds-swift/blob/53c577a0f9c8b86c02420e9818c39af2ca103381/readium-opds/OPDS2Parser.swift#L452-L458), you will see that the JSON value called `v` is getting casted to `[[String: Any]]`.

This is where it fails, only a cast to `[String: Any]` could be successful with the provided JSON.

This snippet works with the feed used in this issue:
```
case "links":
  guard let link = v as? [String: Any] else {
    throw OPDS2ParserError.invalidCollection
  }
  c.links.append(try parseLink(linkDict: link))
```

So, my question is: does the JSON `links` key above could have multiple link entry?

**Comment by HadrienGardeur** [comment]
This is probably an error on the preprod catalog since `links` should always be an array.

**Comment by gbugniot** [comment]
I close this one since it was an issue due to the feed itself.
