### ISSUE TITLE
JSON serialization of Publication is missing specification properties

### ISSUE THREAD

**Issue by mmenu-mantano** [readium/r2-shared-swift#41]
When serializing a Publication, a lot of properties from the JSON schema specification are missing.
The JSON serialization should be reviewed and completed, adapting the existing unit tests.

> Core specification: https://readium.org/webpub-manifest/
> Default metadata context: https://readium.org/webpub-manifest/contexts/default/
> JSON Schema: https://readium.org/webpub-manifest/schema/publication.schema.json
> The JSON Schema is used more and more as the reference document these days.

**Comment by aferditamuriqi** [comment]
I believe this is the issue https://github.com/readium/r2-shared-swift/issues/36 we had for this already.

**Comment by mmenu-mantano** [comment]
I'm not sure how #36 relates to JSON serialization conformance to the spec, but it could be. Should I close this one and comment on #36 for this specific problem?

**Comment by HadrienGardeur** [comment]
Well here's my take on this:

- #36 is about the discussion that we had in December about aligning the in-memory model between platforms and with the RWPM spec
- the current issue is about the JSON output for these same models

IMO they go hand in hand but this is not the same issue as #36.

**Comment by mmenu-mantano** [comment]
@HadrienGardeur Is the JSON schema hosted by Readium supposed to fit the EPUB 3 specification tightly?

[Compared to the spec](http://www.idpf.org/epub/301/spec/epub-publications.html#meta-properties-rendering), "flow" is named "overflow", and "scrolled-doc" is named "scrolled".

https://readium.org/webpub-manifest/schema/extensions/epub/metadata.schema.json
```
"overflow": {
  "description": "Suggested method for handling overflow while displaying the linked resource",
  "type": "string",
  "enum": [
    "auto",
    "paginated",
    "scrolled",
    "scrolled-continuous"
  ]
}
```

This makes the parsing then JSON serialization more complicated than necessary.

Also, the models don't seem to follow the spec either:
```
public enum RenditionFlow: String, Encodable {
    case paginated = "paginated"
    case continuous = "continuous"
    case document = "document"
    case fixed = "fixed" // Is that correct?
}
```

I don't know where those values come from since it's supposed to be used to parse rendition:flow.

I'm fixing some of it in a dedicated branch fixes/json, as it might be breaking changes. I guess it's not really used in R2 right now though.

**Comment by HadrienGardeur** [comment]
@mmenu-mantano it's an entirely different specification, it's not meant to follow the EPUB 3 spec exactly.

`flow` is named `overflow` because it's closer to that notion in CSS and makes more sense than `flow`.
`fixed` is also more natural than `pre-paginated` since we always talk about fixed layout publications, not pre-paginated publications.

For parsing, I don't think it necessarily makes things more complicated since it's better to use switch/case anyway since we can't allow just any value.

For the JSON serialization, you shouldn't have to change values at all.

**Comment by HadrienGardeur** [comment]
The missing link that you might be looking for is https://readium.org/architecture/streamer/parser/metadata

**Comment by mmenu-mantano** [comment]
Thanks, this document will be really helpful!

So, the ideal goal is to have an in-memory model of the publication following RWPM and not EPUB3 spec, then?

The mismatch does complicate things a bit because using Swift enums we have the parsing + serialization automatically handled without switch/case:

```
public enum RenditionFlow: String, Encodable {
    case auto = "auto"
    case paginated = "paginated"
    case scrolledDoc = "scrolled-doc"
    case scrolledContinuous = "scrolled-continuous"
}

// parsing
let flow = RenditionFlow(rawValue: "paginated")
// "serialization", used by the JSONEncoder
flow.rawValue
```

But it doesn't matter, I think it's fine to add a parseFromEPUB or something similar to RenditionFlow.
However, right now the model is part EPUB3, part RWPM which complicates thing. I will do some changes to fit RWPM better.

**Comment by HadrienGardeur** [comment]
> So, the ideal goal is to have an in-memory model of the publication following RWPM and not EPUB3 spec, then?

Indeed.

> The mismatch does complicate things a bit because using Swift enums we have the parsing + serialization automatically handled without switch/case

EPUB 3 is just one format among others. As you can see in the document dedicating to parsing EPUB, quite a few things are handled differently in EPUB 2.

The current version of the streamer can also parse CBZ and RWPM itself and in the future we'll have to parse WP as well.

**Comment by mmenu-mantano** [comment]
I see, then the shared model should stay pure and the mapping from EPUB 3 properties segregated to the EPUB parser in the streamer.

**Comment by HadrienGardeur** [comment]
In November/December 2018 we had a series of calls dedicated to the models, which resulted (among other things) in opening issue #36.

You might want to take a look at these meeting notes and/or listen to these calls:

- https://docs.google.com/document/d/1mHMwJJq3Lypi36bzm3_6LM4wQX8iygdbTTy-S8fya5o/edit
- https://docs.google.com/document/d/1AJnLLjE8z88LJ54af5TgZLExISaItlgJyLP_nx36iqo/edit
