### ISSUE TITLE
Add a way to forward Publication warnings

### ISSUE THREAD

**Issue by mickael-menu-mantano** [readium/r2-shared-swift#60]
Sometimes warnings might be issued by a parser when parsing a Publication model (eg. "the cover is encrypted").

Right now, we don't have any way to send such information to the host app to warn the user.

I suggest adding `Publication.warnings: [LocalizedError]` (not part of RWPM). Using `LocalizedError` instead of `Error` forces to provide an actual error message for the user. And by not having an enum in `r2-shared-swift`, each parser can add their own error type for custom errors.

To check a specific error, it could be used like this `publication.warnings.contains(ParsingError.encryptedTOC)`

**Comment by mickael-menu** [comment]
Here's a Kotlin implementation (not yet merged): https://github.com/readium/r2-shared-kotlin/blob/fixes/publication-models/r2-shared/src/main/java/org/readium/r2/shared/util/logging/WarningLogger.kt

**Comment by mickael-menu** [comment]
`WarningLogger` is now available on iOS as well.
